version: '2'
services:
    apprefactory-app:
        image: apprefactory
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://apprefactory-postgresql:5432/apprefactory
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=apprefactory-elasticsearch:9300
        ports:
            - 8080:8080
    apprefactory-postgresql:
        extends:
            file: postgresql.yml
            service: apprefactory-postgresql
    apprefactory-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: apprefactory-elasticsearch
